services:
  backend:
    build:
      context: ./backend
      dockerfile: back.dockerfile
    ports:
      - 3005:3005
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: front.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
